apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bws-k8s-keystone-auth
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - clusters: {}
  template:
    metadata:
      name: bws-k8s-keystone-auth
    spec:
      project: default
      source:
        repoURL: 'https://valiton-k8s-blueprints.github.io/charts'
        chart: 'bws-k8s-keystone-auth'
        targetRevision: '0.1.0'
        helm:
          releaseName: bws-k8s-keystone-auth
          values: |
            imageTag: v1.34.1
            authUrl: {{.metadata.annotations.openstack_auth_url}}
      destination:
        name: '{{.name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
