ports:
  web:
    port: 80
    proxyProtocol:
      insecure: true

  websecure:
    port: 443
    proxyProtocol:
      insecure: true

ingressRoute:
  dashboard:
    enabled: false

ingressClass:
  enabled: false

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: false
  kubernetesIngressNGINX:
    enabled: true
    watchIngressWithoutClass: true
  kubernetesGateway:
    enabled: false

log:
  level: INFO

accessLog:
  enabled: true

metrics:
  prometheus:
    enabled: true

service:
  spec:
    type: LoadBalancer
  annotations:
    loadbalancer.openstack.org/proxy-protocol: "true"
    loadbalancer.openstack.org/enable-health-monitor: "true"

extraObjects:
  - apiVersion: networking.k8s.io/v1
    kind: IngressClass
    metadata:
      name: nginx
      annotations:
        ingressclass.kubernetes.io/is-default-class: "true"
    spec:
      controller: k8s.io/ingress-nginx
