clusterSecretStore:
  name: cluster-secrets
  namespaces:
    matchLabels:
      access-cluster-secrets: "true"
  cinderCsiPlugin:
    enabled: false
externalDns:
  enabled: true
  namespace: external-dns
  secretName: external-dns-designate-secret
  cloudName: cloud
certManagerDesignateWebhook:
  enabled: true
  namespace: cert-manager
  secretName: designate-auth
openstackCloudControllerManager:
  enabled: false
