apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-crs
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: enable_external_secrets
              operator: In
              values: ['true']
  template:
    metadata:
      name: external-secrets-crs
      finalizers:
        - resources-finalizer.argocd.argoproj.io/background
    spec:
      project: default
      source:
        repoURL: 'https://valiton-k8s-blueprints.github.io/charts'
        chart: 'aws-external-secrets-crs'
        targetRevision: '0.1.0'
      destination:
        name: '{{.name}}'
      syncPolicy:
        automated:
          allowEmpty: true
        syncOptions:
        - CreateNamespace=true
        retry:
          backoff:
            duration: 1m
          limit: 60
